version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWOR
    steps:
      - setup_remote_docker
      - run:
          name: Build and push frontend application image
          command: |
            git clone https://github.com/springsandbox/spring-petclinic-angular.git
            cd ./spring-petclinic-angular
            DOCKER_TAG=$(echo $CIRCLE_SHA1 | head -c 7)
            docker build -t $DOCKERHUB_USERNAME/petclinic_frontend:$DOCKER_TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/petclinic_frontend:$DOCKER_TAG
workflows:
  version: 2
  build:
    jobs:
      - build